
# CentOS Stream 9 with Nodejs18
# docker build --platform linux/amd64 --build-arg GITHUB_TOKEN=value --build-arg GITHUB_USER=value GIT_BRANCH=value -t quay.io/vboulos/acmqe-automation/clc:release-2.10 -f clc-ui/Dockerfile .


FROM quay.io/vboulos/acmqe-automation/clc-ui:main

RUN echo "runniing"

CMD ["/bin/bash"]

